# Generated by Django 3.0.6 on 2020-05-31 22:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tangoweb', '0002_competition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competition',
            new_name='UserCompetition',
        ),
        migrations.RenameModel(
            old_name='Practice',
            new_name='UserPractice',
        ),
    ]
