# Generated by Django 3.0.6 on 2020-06-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangoweb', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompetition',
            name='attempt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercompetitionboard',
            name='attempt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
